//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarangayInformationSystem.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_bisEntities : DbContext
    {
        public db_bisEntities()
            : base("name=db_bisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<civil_status> civil_status { get; set; }
        public DbSet<gender> gender { get; set; }
        public DbSet<purok> purok { get; set; }
        public DbSet<Request> Request { get; set; }
        public DbSet<sitio> sitio { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<user_detail> user_detail { get; set; }
    }
}
