//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarangayInformationSystem.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class gender
    {
        public int gender_id { get; set; }
        public string gender_description { get; set; }
        public string gender_code { get; set; }
    }
}
