//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarangayInformationSystem.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class purok
    {
        public int purok_id { get; set; }
        public Nullable<int> purok_no { get; set; }
        public string purok_name { get; set; }
        public string purok_leader { get; set; }
    }
}
