//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarangayInformationSystem.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_detail
    {
        public int user_detail_auto_id { get; set; }
        public string user_detail_id { get; set; }
        public string user_lname { get; set; }
        public string user_fname { get; set; }
        public string user_mname { get; set; }
        public string user_suffix { get; set; }
        public Nullable<int> user_age { get; set; }
        public string user_email { get; set; }
        public string user_username { get; set; }
        public string user_purok { get; set; }
        public string user_houseno { get; set; }
        public string user_sitio { get; set; }
        public string user_purokleader { get; set; }
        public Nullable<System.DateTime> user_date_birth { get; set; }
        public string user_gender { get; set; }
        public string user_civil_status { get; set; }
        public string user_nationality { get; set; }
        public string user_religion { get; set; }
        public string user_place_birth { get; set; }
        public string user_place_province { get; set; }
        public string user_place_city { get; set; }
        public string user_address_unit_no { get; set; }
        public string user_address_house_no { get; set; }
        public string user_address_street { get; set; }
        public string user_address_subdivision { get; set; }
        public string user_address_brgy { get; set; }
        public string user_address_city { get; set; }
        public string user_address_province { get; set; }
        public string user_address_country { get; set; }
        public Nullable<int> user_zip_code { get; set; }
        public string user_mobile_no { get; set; }
        public string user_tel_no { get; set; }
        public string user_blood { get; set; }
        public string user_height { get; set; }
        public string user_weight { get; set; }
        public Nullable<int> user_is_malnourish { get; set; }
        public Nullable<int> user_is_PWD { get; set; }
        public Nullable<int> user_is_covid_vax { get; set; }
        public string user_comorbidities { get; set; }
        public string user_other_vax { get; set; }
        public Nullable<int> user_has_national_id { get; set; }
        public Nullable<int> user_registered { get; set; }
        public string user_precinct { get; set; }
        public Nullable<int> user_has_sss { get; set; }
        public Nullable<int> user_has_philhealth { get; set; }
        public Nullable<int> user_is_4ps { get; set; }
        public string user_is_uct { get; set; }
        public string user_others_indigent { get; set; }
    }
}
